shell /usr/bin/zsh
term xterm-256color

font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500

# Appearance
background_opacity 0.7
dynamic_background_opacity yes
inactive_text_alpha 0.8
hide_window_decorations yes
window_padding_width 12 16
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 2000

# Cursor
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# Performance (RTX 4060)
repaint_delay 8
input_delay 2
sync_to_monitor yes

# Matugen colors
include colors-matugen.conf

# 覆盖 matugen 的背景色，与 ghostty 默认主题一致
background #282c34

# 让 claude code 可以在tmux中shift+return换行
# map shift+enter send_text all \x1b\r

