# Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Notification daemon
exec-once = swaync

# Wallpaper
exec-once = swww-daemon & sleep 1 && swww img ~/.config/hypr/wallpapers/wallhaven-w51676.png

# Idle management
exec-once = hypridle

# Clipboard history
exec-once = wl-paste --watch cliphist store

# StatusNotifierWatcher (tray support)
exec-once = dbus-send --session --print-reply --dest=org.kde.kded6 /kded org.kde.kded6.loadModule string:statusnotifierwatcher

# Status bar
exec-once = ~/.config/waybar/launch.sh

# Input method
exec-once = fcitx5 -d
