decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.88
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.08
    dim_special = 0.4

    blur {
        enabled = true
        size = 4
        passes = 4
        new_optimizations = on
        ignore_opacity = true
        xray = true
    }

    shadow {
        enabled = true
        range = 38
        render_power = 3
        color = rgba(adc6ff30)
        color_inactive = rgba(00000035)
        offset = 0 4
        scale = 0.98
    }
}
