general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = $primary $tertiary 45deg
    col.inactive_border = $outline_variant
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = $primary $tertiary 45deg
    col.border_inactive = $outline_variant
    col.border_locked_active = $primary $tertiary 45deg
    col.border_locked_inactive = $outline_variant

    groupbar {
        enabled = true
        font_size = 14
        height = 22
        gradients = true
        gradient_rounding = 8
        gradient_round_only_edges = true
        indicator_height = 0
        indicator_gap = 0
        render_titles = true
        scrolling = true
        text_color = $on_primary_container
        col.active = $primary_container
        col.inactive = $surface_container_high
    }
}
